import { Router } from "express";
import AuthRoute from "./auth";
import UsersRoute from "./users";
import AdminsRoute from "./admins";
import PrivilegesRoute from "./privileges";
import CategoryRoute from "./categories";
import PromoCodeRoute from "./promocodes";
import ExtraRoute from "./extras";
import CurrencyRoute from "./currencies";
import ProfileRoute from "./profile";
import HomeRoute from "./homePage";
import TourRoute from "./tours";
const router = Router();
router.use("/auth", AuthRoute);
router.use("/users", UsersRoute);
router.use("/admins", AdminsRoute);
router.use("/privileges", PrivilegesRoute);
router.use("/categories", CategoryRoute);
router.use("/promocodes", PromoCodeRoute);
router.use("/currencies", CurrencyRoute);
router.use("/extras", ExtraRoute);
router.use("/profile", ProfileRoute);
router.use("/homePage", HomeRoute);
router.use("/tours", TourRoute);
export default router;
